src/Microdownload/Areas/Panel/Controllers/LoginController.cs
using Microdownload.Common.GuardToolkit;
using Microdownload.Services.Contracts.Identity;
using Microdownload.ViewModels.Identity.Settings;
using Microdownload.ViewModels.Identity;
using DNTBreadCrumb.Core;
using DNTCaptcha.Core;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using System.Threading.Tasks;
using DNTCommon.Web.Core;
using Microdownload.Areas.Panel;

namespace Microdownload.Areas.Panel.Controllers
{
    [Area(AreaConstants.PanelArea)]
    [AllowAnonymous]
    [BreadCrumb(Title = "ورود به سیستم", UseDefaultRouteUrl = true, Order = 0)]
    public class LoginController : Controller
    {
        private readonly ILogger<LoginController> _logger;
        private readonly IApplicationSignInManager _signInManager;
        private readonly IApplicationUserManager _userManager;
        private readonly IOptionsSnapshot<SiteSettings> _siteOptions;

        public LoginController(
            IApplicationSignInManager signInManager,
            IApplicationUserManager userManager,
            IOptionsSnapshot<SiteSettings> siteOptions,
            ILogger<LoginController> logger)
        {
            _signInManager = signInManager;
            _signInManager.CheckArgumentIsNull(nameof(_signInManager));

            _userManager = userManager;
            _userManager.CheckArgumentIsNull(nameof(_userManager));

            _siteOptions = siteOptions;
            _siteOptions.CheckArgumentIsNull(nameof(_siteOptions));

            _logger = logger;
            _logger.CheckArgumentIsNull(nameof(_logger));
        }

        [BreadCrumb(Title = "ایندکس", Order = 1)]
        [NoBrowserCache]
        public IActionResult Index(string returnUrl = null)
        {
            ViewData["ReturnUrl"] = "/";
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateDNTCaptcha(CaptchaGeneratorLanguage = DNTCaptcha.Core.Providers.Language.Persian)]
        public async Task<IActionResult> Index(LoginViewModel model, string returnUrl = null)
        {
            ViewData["ReturnUrl"] = returnUrl;
            if (ModelState.IsValid)
            {
                var user = await _userManager.FindByNameAsync(model.Username);
                if (user == null)
                {
                    ModelState.AddModelError(string.Empty, "کد کاربری و یا کلمه‌ی عبور وارد شده معتبر نیستند.");
                    return View(model);
                }

                if (!user.IsActive)
                {
                    ModelState.AddModelError(string.Empty, "اکانت شما غیرفعال شده‌است.");
                    return View(model);
                }

                if (_siteOptions.Value.EnableEmailConfirmation &&
                    !await _userManager.IsEmailConfirmedAsync(user))
                {
                    ModelState.AddModelError("", "لطفا به پست الکترونیک خود مراجعه کرده و ایمیل خود را تائید کنید!");
                    return View(model);
                }

                var result = await _signInManager.PasswordSignInAsync(
                                        model.Username,
                                        model.Password,
                                        model.RememberMe,
                                        lockoutOnFailure: true);
                if (result.Succeeded)
                {
                    _logger.LogInformation(1, $"{model.Username} logged in.");
                    if (Url.IsLocalUrl(returnUrl))
                    {
                        return Redirect(returnUrl);
                    }
                    return RedirectToAction(nameof(HomeController.Index), "Home");
                }

                if (result.RequiresTwoFactor)
                {
                    return RedirectToAction(
                        nameof(TwoFactorController.SendCode),
                        "TwoFactor",
                        new { ReturnUrl = returnUrl, RememberMe = model.RememberMe });
                }

                if (result.IsLockedOut)
                {
                    _logger.LogWarning(2, $"{model.Username} قفل شده‌است.");
                    return View("~/Areas/Panel/Views/TwoFactor/Lockout.cshtml");
                }

                if (result.IsNotAllowed)
                {
                    ModelState.AddModelError(string.Empty, "عدم دسترسی ورود.");
                    return View(model);
                }

                ModelState.AddModelError(string.Empty, "کد کاربری و یا کلمه‌ی عبور وارد شده معتبر نیستند.");
                return View(model);
            }

            // If we got this far, something failed, redisplay form
            return View(model);
        }

        public async Task<IActionResult> LogOff()
        {
            var user = User.Identity.IsAuthenticated ? await _userManager.FindByNameAsync(User.Identity.Name) : null;
            await _signInManager.SignOutAsync();
            if (user != null)
            {
                await _userManager.UpdateSecurityStampAsync(user);
                _logger.LogInformation(4, $"{user.UserName} logged out.");
            }

            return RedirectToAction(nameof(HomeController.Index), "Home");
        }
    }
}

src/Microdownload/Controllers/RegisterController.cs
using Microdownload.Common.GuardToolkit;
using Microdownload.Common.IdentityToolkit;
using Microdownload.Entities.Identity;
using Microdownload.Services.Contracts.Identity;
using Microdownload.ViewModels.Identity;
using DNTBreadCrumb.Core;
using DNTCaptcha.Core;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using System.Threading.Tasks;
using System;
using Microdownload.ViewModels.Identity.Emails;
using Microdownload.ViewModels.Identity.Settings;
using DNTPersianUtils.Core;
using DNTCommon.Web.Core;
using Microdownload.Areas.Panel;
using Microdownload.Services.Identity;
using System.ComponentModel;
using System.Linq;

namespace Microdownload.Controllers
{
    [DisplayName("افزودن کاربر جدید")]

    public class RegisterController : Controller
    {
        private readonly IEmailSender _emailSender;
        private readonly ILogger<RegisterController> _logger;
        private readonly IApplicationUserManager _userManager;
        private readonly IPasswordValidator<User> _passwordValidator;
        private readonly IUserValidator<User> _userValidator;
        private readonly IOptionsSnapshot<SiteSettings> _siteOptions;
        private readonly IApplicationRoleManager _roleManager;

        public RegisterController(
            IApplicationUserManager userManager,
            IPasswordValidator<User> passwordValidator,
            IUserValidator<User> userValidator,
            IEmailSender emailSender,
            IOptionsSnapshot<SiteSettings> siteOptions,
            ILogger<RegisterController> logger,
            IApplicationRoleManager roleManager)
        {
            _userManager = userManager;
            _userManager.CheckArgumentIsNull(nameof(_userManager));

            _passwordValidator = passwordValidator;
            _passwordValidator.CheckArgumentIsNull(nameof(_passwordValidator));

            _userValidator = userValidator;
            _userValidator.CheckArgumentIsNull(nameof(_userValidator));

            _emailSender = emailSender;
            _emailSender.CheckArgumentIsNull(nameof(_emailSender));

            _logger = logger;
            _logger.CheckArgumentIsNull(nameof(_logger));

            _siteOptions = siteOptions;
            _siteOptions.CheckArgumentIsNull(nameof(_siteOptions));

            _roleManager = roleManager;
            _roleManager.CheckArgumentIsNull(nameof(_roleManager));

        }
    

    /// <summary>
    /// For [Remote] validation
    /// </summary>
    [AjaxOnly, HttpPost, ValidateAntiForgeryToken]
    [ResponseCache(Location = ResponseCacheLocation.None, NoStore = true)]
    public async Task<IActionResult> ValidateUsernameForRegister(string username)
    {

        var all = await _userManager.GetAllUsersAsync();
        var result = (from p in all
                      where p.NormalizedUserName == username.ToUpper()
                      select p);
        return Json(result.Any() ? "این نام کاربری در سیستم کاتب ثبت شده است" : "true");
    }




    /// <summary>
    /// For [Remote] validation
    /// </summary>
    [AjaxOnly, HttpPost, ValidateAntiForgeryToken]
    [ResponseCache(Location = ResponseCacheLocation.None, NoStore = true)]
    [BreadCrumb(Title = "اعتبار سنجی نام کاربری", Order = 1)]
    [DisplayName("اعتبار سنجی نام کاربری")]
    public async Task<IActionResult> ValidateUsername(string username, string email)
    {
        var result = await _userValidator.ValidateAsync(
            (UserManager<User>)_userManager, new User { UserName = username, Email = email });
        return Json(result.Succeeded ? "true" : result.DumpErrors(useHtmlNewLine: true));
    }

    /// <summary>
    /// For [Remote] validation
    /// </summary>
    [AjaxOnly, HttpPost, ValidateAntiForgeryToken]
    [ResponseCache(Location = ResponseCacheLocation.None, NoStore = true)]
    [BreadCrumb(Title = "اعتبار سنجی پسورد", Order = 1)]
    [DisplayName("اعتبار سنجی پسورد")]

    public async Task<IActionResult> ValidatePassword(string password, string username)
    {
        var result = await _passwordValidator.ValidateAsync(
            (UserManager<User>)_userManager, new User { UserName = username }, password);
        return Json(result.Succeeded ? "true" : result.DumpErrors(useHtmlNewLine: true));
    }

    [BreadCrumb(Title = "تائید ایمیل", Order = 1)]
    [DisplayName("تائید ایمیل")]

    public async Task<IActionResult> ConfirmEmail(string userId, string code)
    {
        if (userId == null || code == null)
        {
            return View("Error");
        }

        var user = await _userManager.FindByIdAsync(userId);
        if (user == null)
        {
            return View("NotFound");
        }

        var result = await _userManager.ConfirmEmailAsync(user, code);
        return View(result.Succeeded ? nameof(ConfirmEmail) : "Error");
    }


        [BreadCrumb(Title = "ثبت نام با کد معرف", Order = 1)]
        [DisplayName("ثبت نام با کد معرف")]

        public async Task<IActionResult> Index(string UserName)
        {
          var referrer= await _userManager.FindByNameAsync(UserName);
            var DisplayName = referrer.DisplayName;
            ViewBag.NameOfUser = DisplayName;

            var regModel = new RegisterViewModel();
            regModel.Referrer = referrer.UserName;
            return View(regModel);
        }




        [BreadCrumb(Title = "تائیدیه ایمیل", Order = 1)]
    [DisplayName("تائیدیه ایمیل")]
    public IActionResult ConfirmedRegisteration()
    {
        return View();
    }
    [BreadCrumb(Title = "ایندکس", Order = 1)]
    [DisplayName("ایندکس")]

    [HttpPost]
    [ValidateAntiForgeryToken]
    [ValidateDNTCaptcha(CaptchaGeneratorLanguage = DNTCaptcha.Core.Providers.Language.Persian)]
    public async Task<IActionResult> Index(RegisterViewModel model)
    {
        var cuser = User.Identity.GetUserName();

        if (ModelState.IsValid)
        {
           // var cuserId = int.Parse(_userManager.GetCurrentUserId());
                var user = new User
            {
                UserName = model.Username,
                Email = model.Email,
                FirstName = model.FirstName,
                LastName = model.LastName,
                PhoneNumber = model.PhoneNumber,
                MeliCode = model.MeliCode
            };
            var result = await _userManager.CreateAsync(user, model.Password);
            if (result.Succeeded)
            {
                _logger.LogInformation(3, $"{user.UserName} created a new account with password.");

                if (_siteOptions.Value.EnableEmailConfirmation)
                {
                    var code = await _userManager.GenerateEmailConfirmationTokenAsync(user);
                    //ControllerExtensions.ShortControllerName<RegisterController>(), //todo: use everywhere .................

                    await _emailSender.SendEmailAsync(
                       email: user.Email,
                       subject: "لطفا اکانت خود را تائید کنید",
                       viewNameOrPath: "~/Areas/Panel/Views/EmailTemplates/_RegisterEmailConfirmation.cshtml",
                       model: new RegisterEmailConfirmationViewModel
                       {
                           User = user,
                           EmailConfirmationToken = code,
                           EmailSignature = _siteOptions.Value.Smtp.FromName,
                           MessageDateTime = DateTime.UtcNow.ToLongPersianDateTimeString()
                       });

                    return RedirectToAction(nameof(ConfirmYourEmail));
                }
                return RedirectToAction(nameof(ConfirmedRegisteration));
            }

            foreach (var error in result.Errors)
            {
                ModelState.AddModelError(string.Empty, error.Description);
            }
        }
        return View(model);
    }

    [BreadCrumb(Title = "ایمیل خود را تائید کنید", Order = 1)]
    [DisplayName("ایمیل خود را تائید کنید")]

    public IActionResult ConfirmYourEmail()
    {
        return View();
    }
}
}

src/Microdownload/Views/Register/ConfirmEmail.cshtml
@{
    ViewData["Title"] = "تائید مشخصات کاربری";
}

<div class="panel panel-default top30 col-md-6 col-md-push-3">
    <div class="panel-heading">
        <h3 class="panel-title">@ViewData["Title"]</h3>
    </div>
    <div class="panel-body">
        با تشکر.
        اطلاعات کاربری شما با موفقیت تائید شدند.
        @if (!User.Identity.IsAuthenticated)
        {
            <span>لطفا جهت ورود به سیستم <a asp-controller="Login" asp-action="Index">اینجا</a> کلیک کنید.</span>
        }
    </div>
</div>

src/Microdownload/Views/Register/ConfirmYourEmail.cshtml
<div class="panel panel-default top30 col-md-6 col-md-push-3">
    <div class="panel-heading">
        <h3 class="panel-title">با تشکر!</h3>
    </div>
    <div class="panel-body">
        ثبت نام نماینده با موفقیت انجام شد. لطفا از نماینده بخواهید به میل باکس خود مراجعه کرده و ایمیل خود را تائید نماید. همچنین شما می توانید از بخش مدیریت نمایندگان ایمیل را تایید نمایید
        <partial name="_PickupFolder" />
    </div>
</div>

src/Microdownload/Views/Register/ConfirmedRegisteration.cshtml
<div class="panel panel-default top30 col-md-6 col-md-push-3">
    <div class="panel-heading">
        <h3 class="panel-title">با تشکر!</h3>
    </div>
    <div class="panel-body">
        ثبت نام با موفقیت انجام شد.
        لطفا جهت ورود به سیستم <a asp-controller="Login" asp-action="Index">اینجا</a> کلیک کنید.
    </div>
</div>

src/Microdownload/Views/Register/Index.cshtml
@model RegisterViewModel

@{
    ViewData["Title"] = "ثبت نام کاربر جدید";
}


<section class="header-breadcrumb bgimage overlay overlay--dark">
    <div class="bg_image_holder"><img src="~/Client/img/breadcrumb1.jpg" alt=""></div>
    <div class="mainmenu-wrapper">

        <partial name="_UserPublicMenu" />

    </div><!-- ends: .mainmenu-wrapper -->
    <div class="breadcrumb-wrapper content_above">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h1 class="page-title">ثبت نام در آموزشگاه</h1>
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="#">خانه</a></li>
                            <li class="breadcrumb-item active" aria-current="page">@ViewData["Title"]</li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div><!-- ends: .breadcrumb-wrapper -->
</section>

<section class="add-listing-wrapper border-bottom section-bg section-padding-strict">

    <div class="container">
        <div class="container">
            <form asp-controller="Register"
                  asp-action="Index"
                  method="post"
                  class="form-horizontal top30">
                @{ await Html.RenderPartialAsync("_CustomValidationSummary").ConfigureAwait(false); }
                <div class="row">


                    <div class="col-lg-10 offset-lg-1">
                        <div class="atbd_content_module">
                            <div class="atbd_content_module__tittle_area">
                                <div class="atbd_area_title">
                                    <h4><span class="la la-user"></span>اطلاعات عمومی </h4>
                                    <h6><span class="la la-user"></span> معرف شما : @ViewBag.NameOfUser </h6>
                                </div>
                            </div>
                            <div class="atbdb_content_module_contents">

                                <div class="form-group hidden">
                                    <div class="input-group hidden">
                                        <input dir="rtl" asp-for="Referrer" class="form-control" hidden="hidden"/>
                                    </div>
                                </div>


                                <div class="form-group">
                                    <label asp-for="FirstName" class="form-label"></label>
                                    <div class="input-group">
                                        <input dir="rtl" asp-for="FirstName" class="form-control" />
                                    </div>
                                    <span asp-validation-for="FirstName" class="text-danger"></span>
                                </div>


                                <div class="form-group">
                                    <label asp-for="LastName" class="form-label"></label>
                                    <div class="input-group">
                                        <input dir="rtl" asp-for="LastName" class="form-control" />
                                    </div>
                                    <span asp-validation-for="LastName" class="text-danger"></span>

                                </div>




                            </div><!-- ends: .atbdb_content_module_contents -->
                        </div><!-- ends: .atbd_content_module -->
                    </div><!-- ends: .col-lg-10 -->

                    <div class="col-lg-10 offset-lg-1">
                        <div class="atbd_content_module">
                            <div class="atbd_content_module__tittle_area">
                                <div class="atbd_area_title">
                                    <h4><span class="la la-user"></span>اطلاعات ورود</h4>
                                </div>
                            </div>
                            <div class="atbdb_content_module_contents">

                                <div class="form-group">
                                    <label asp-for="Username" class="col-md-3 control-label"></label>
                                    <div>
                                        <input dir="ltr" asp-for="Username" class="form-control" />
                                        <span asp-validation-for="Username" class="text-danger"></span>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label asp-for="Password" class="col-md-3 control-label"></label>
                                    <div>
                                        <input dir="ltr" asp-for="Password" class="form-control" />
                                        <span asp-validation-for="Password" class="text-danger"></span>
                                    </div>
                                </div>


                                <div class="form-group">
                                    <label asp-for="ConfirmPassword" class="col-md-3 control-label"></label>
                                    <div>
                                        <input dir="ltr" asp-for="ConfirmPassword" class="form-control" />
                                        <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
                                    </div>
                                </div>







                            </div><!-- ends: .atbdb_content_module_contents -->
                        </div><!-- ends: .atbd_content_module -->
                    </div><!-- ends: .col-lg-10 -->

                    <div class="col-lg-10 offset-lg-1">
                        <div class="atbd_content_module">
                            <div class="atbd_content_module__tittle_area">
                                <div class="atbd_area_title">
                                    <h4><span class="la la-user"></span>اطلاعات تماس</h4>
                                </div>
                            </div>
                            <div class="atbdb_content_module_contents">
                                <div class="form-group">
                                    <label asp-for="PhoneNumber" class="form-label"></label>
                                    <div class="input-group top15">
                                        <input dir="ltr" asp-for="PhoneNumber" class="form-control" />
                                    </div>
                                    <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                                </div>

                                <div class="form-group">
                                    <label asp-for="Email" class="form-label"></label>
                                    <input dir="ltr" asp-for="Email" type="email" class="form-control" required>
                                    <span asp-validation-for="Email" class="text-danger"></span>

                                </div>

                            </div>
                        </div><!-- ends: .atbd_content_module -->
                    </div><!-- ends: .col-lg-10 -->
                </div>

                <div class="col-lg-10 offset-lg-1  text-center">
                    <div class="atbd_content_module">
                        <div class="atbd_content_module__tittle_area">
                            <div class="atbd_area_title">
                                <h4><span class="la la-calendar-check-o"></span> بخش امنیت</h4>
                            </div>
                        </div>
                        <div class="atbdb_content_module_contents ">
                            <div class="form-group">
                                <label class="col col-md-3 control-label">
                                    کد امنیتی را وارد نمائید
                                </label>
                                <div class="controls  text-center">
                                    <dnt-captcha asp-captcha-generator-max="1000"
                                                 asp-captcha-generator-min="1"
                                                 asp-captcha-generator-language="Persian"
                                                 asp-font-name="Tahoma"
                                                 asp-font-size="20"
                                                 asp-fore-color="#333333"
                                                 asp-back-color="#ccc"
                                                 asp-text-box-class="text-box single-line form-control"
                                                 asp-text-box-template="<div class='input-group'><span class='input-group-addon'><span class='glyphicon glyphicon-lock'></span></span>{0}</div>"
                                                 asp-validation-message-class="text-danger" />
                                </div>
                            </div>
                        </div><!-- ends: .atbdb_content_module_contents -->
                    </div><!-- ends: .atbd_content_module -->
                </div><!-- ends: .col-lg-10 -->


                <div class="col-lg-10 offset-lg-1 text-center">


                    <div class="btn_wrap  m-top-25">
                        <button type="submit" class="btn btn-primary btn-lg">ثبت نام اولیه</button>
                    </div>
                </div><!-- ends: .col-lg-10 -->
            </form>
        </div>
    </div>
</section><!-- ends: .add-listing-wrapper -->



@section Scripts
    {
    <script type="text/javascript">
        function triggerRemoteValidation() {
            $('#@nameof(RegisterViewModel.Username)').removeData('previousValue');
            $('form').validate().element('#@nameof(RegisterViewModel.Username)');

            $('#@nameof(RegisterViewModel.Email)').removeData('previousValue');
            $('form').validate().element('#@nameof(RegisterViewModel.Email)');
        }
    </script>
}