src/Microdownload/Areas/Panel/Controllers/CourseController.cs
using System;
using System.ComponentModel;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using DNTBreadCrumb.Core;
using DNTCommon.Web.Core;
using Microdownload.Common.IdentityToolkit;
using Microdownload.DataLayer.Context;
using Microdownload.Services;
using Microdownload.Services.Identity;
using Microdownload.ViewModels;
using Microdownload.ViewModels.Identity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using NToastNotify;

namespace Microdownload.Areas.Panel.Controllers
{
    [Area(AreaConstants.PanelArea)]
    [Authorize(Policy = ConstantPolicies.DynamicPermission)]
    [BreadCrumb(Title = "دوره ها", UseDefaultRouteUrl = true, Order = 0)]
    [DisplayName("دوره ها")]
    public class CoursesController : Controller
    {
        private const string CourseNotFound = "اطلاعات درخواستی یافت نشد.";

        private readonly ICourseService _ICourseService;
        private readonly IInstituteService _IInstituteService;

        private readonly IToastNotification _toastNotification;
        private readonly IUnitOfWork _uow;
        private readonly IHostingEnvironment _hostingEnvironment;
        

        public CoursesController(IInstituteService instituteService, IToastNotification toastNotification, ICourseService CourseService, IUnitOfWork uow, IHostingEnvironment hostingEnvironment)
        {
            _toastNotification = toastNotification;
            _ICourseService = CourseService;
            _uow = uow;
            _hostingEnvironment = hostingEnvironment;
            _IInstituteService = instituteService;
        }

        [BreadCrumb(Title = "ایندکس دوره ها", Order = 1)]
        [DisplayName("ایندکس دوره ها")]
        public async Task<IActionResult> Index(Int32? page = 1, Int32? rows = 10)
        {
            var cuser = int.Parse(User.Identity.GetUserId());

            var model = await _ICourseService.GetCourseListAsync(cuser, page.Value, rows.Value);
            ViewBag.TotalRows = model.Paging.TotalItems;
            ViewBag.CurrentPage = page;
            return View(model: model.List);
        }



        [DisplayName("رندر افزودن و ویرایش")]
        [AjaxOnly]
        public async Task<IActionResult> RenderCourse([FromBody]ModelIdViewModel model, IFormFile ImageUrlFile)
        {
            //if (string.IsNullOrWhiteSpace(model?.Id))
            //{
            //    return PartialView("_Create");
            //}

            //var Course = await _ICourseService.GetCourseByIdAsync(int.Parse(model.Id));
            //if (Course == null)
            //{
            //    ModelState.AddModelError("", CourseNotFound);
            //    return PartialView("_Create");
            //}
            //return PartialView("_Create", model: new CourseViewModel { Id = Course.Id, CourseName = Course.CourseName,CreatedDate= Course.CreatedDate,Price= Course.Price,Link=Course.Link });











            var query = await _IInstituteService.GetTeachersListForViewBagAsync();
            ViewData["ListTeacher"] = query;

            var query2 = await _IInstituteService.GetInstituteListForAddAsync();
            ViewData["ListInstitute"] = query2;
            if (string.IsNullOrWhiteSpace(model?.Id))
            {
                return PartialView("_Create");
            }
            var id = int.Parse(model.Id);
            var Cou = await _ICourseService.GetCourseByIdAsync(id).ConfigureAwait(false);
            if (Cou == null)
            {
                ModelState.AddModelError("", "اطلاعات مورد نظر یافت نشد");
                return PartialView("_Create");
            }
            return PartialView("_Create", model: Cou);






        }




        [AjaxOnly]
        [HttpPost]
        [ValidateAntiForgeryToken]
        [DisplayName("افزودن یا ویرایش دوره")]
        
        public virtual async Task<ActionResult> AddCourse(CourseViewModel model, IFormFile ImageUrlFile,int page = 1, int rows = 10)
        {
            var cuser = int.Parse(User.Identity.GetUserId());

            if (!ModelState.IsValid)
            {
                return View();
            }
            IdentityResult result;

                model.CourseStatus = Entities.CourseStatus._FirstRegisteration;

            if (ImageUrlFile != null)
            {
                var fileName = Path.Combine(_hostingEnvironment.WebRootPath + "/images/userpic/", Path.GetFileName(ImageUrlFile.FileName));
                ImageUrlFile.CopyTo(new FileStream(fileName, FileMode.Create));
                model.ImageUrl = "/images/userpic/" + Path.GetFileName(ImageUrlFile.FileName);
            }

                result = _ICourseService.AddCourse(model);
                if (result.Succeeded)
                {
                    await _uow.SaveChangesAsync().ConfigureAwait(false);
                var institutemodel=   await _IInstituteService.GetInstituteByUserIdAsync(cuser);
                InstituteCourseViewModel InstituteCourseVM = new InstituteCourseViewModel();
                InstituteCourseVM.CoursesId = model.Id.Value;
                InstituteCourseVM.InstituteId = institutemodel.Id.Value;
                await _IInstituteService.AddInstituteCourse(model: InstituteCourseVM);

                var CourseModel1 = _ICourseService.GetCourseListAsync(cuser,page,rows).Result.List.Where(c=>c.CourseName==model.CourseName).Single().Id;

                foreach (var item in model.TeacherCourseIdes)
                {
                    var teacher = _IInstituteService.AddCourseToTeacherById(item, CourseModel1.Value);
                    if (teacher.Succeeded)
                    {
                        await _uow.SaveChangesAsync().ConfigureAwait(false);

                    }
                }

                return Json(new { success = true });
                }

            return PartialView("_Create", model: model);
        }


        [DisplayName("ویرایش دوره")]
        
        public virtual async Task<ActionResult> EditCourse(int Id)
        {
              var  Course =await _ICourseService.GetCourseByIdAsync(Id);

            var query = await _IInstituteService.GetTeachersListForViewBagAsync();
            ViewData["ListTeacher"] = query;


            return View(Course);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        [DisplayName("افزودن یا ویرایش دوره")]

        public virtual async Task<ActionResult> EditCourse(CourseViewModel model, IFormFile ImageUrlFile, int page = 1, int rows = 10)
        {
            var cuser = int.Parse(User.Identity.GetUserId());

            if (!ModelState.IsValid)
            {
                return View();
            }
            IdentityResult result;

            if (ImageUrlFile != null)
            {
                var fileName = Path.Combine(_hostingEnvironment.WebRootPath + "/images/userpic/", Path.GetFileName(ImageUrlFile.FileName));
                ImageUrlFile.CopyTo(new FileStream(fileName, FileMode.Create));
                model.ImageUrl = "/images/userpic/" + Path.GetFileName(ImageUrlFile.FileName);
            }

            result = _ICourseService.EditCourse(model);

                if (result.Succeeded)
                {
                    await _uow.SaveChangesAsync().ConfigureAwait(false);


                var CourseModel1 = _ICourseService.GetCourseListAsync(cuser, page, rows).Result.List.Where(c => c.CourseName == model.CourseName).Single().Id;

                foreach (var item in model.TeacherCourseIdes)
                {
                    var teacher = _IInstituteService.AddCourseToTeacherById(item, CourseModel1.Value);
                    if (teacher.Succeeded)
                    {
                        await _uow.SaveChangesAsync().ConfigureAwait(false);

                    }
                }



                _toastNotification.AddInfoToastMessage("ویرایش شد", new NotyOptions()
                    {
                        Layout = "center"
                    });
                    return View(model);
                }
                return View();
            
        }







        }
}

src/Microdownload/Areas/Panel/Views/Courses/EditCourse.cshtml
@model CourseViewModel
@{List<TeacherViewModel> _listTeacher = (List<TeacherViewModel>)ViewData["ListTeacher"]; }
@{var tc = new List<TeacherCourseViewModel>();
    tc = Model.TeacherCourse.ToList();

}
<script type="text/javascript">

    $('.dselect2').select2();
    $('#Amount').number(true, 0);

</script>


<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">@ViewData["Title"]</h3>
    </div>
    <form asp-controller="Courses" enctype="multipart/form-data" asp-action="EditCourse" method="post" class="form-horizontal">


        <div class="panel-body">

            @{ await Html.RenderPartialAsync("_CustomValidationSummary").ConfigureAwait(false); }
            <div align="center">
                <img src="~/images/MicrodownloadIcon.png" class="img-responsive  animated rubberBand" alt="@ViewData["Title"]" />
            </div>

            <h2>اطلاعات شما</h2>
            <hr />




            <div class="form-group">
                @Html.LabelFor(model => model.CourseName, new { @class = "col-md-3 control-label col-md-push-1" })
                <div class="col-md-6">
                    @Html.TextBoxFor(model => model.CourseName, new { @class = "form-control" })
                    <span asp-validation-for="CourseName" class="text-danger"></span>

                </div>
            </div>



            <div class="form-group">
                @Html.LabelFor(model => model.TeacherCourse, new { @class = "col-md-3 control-label col-md-push-1" })
                <div class="col-md-3">
                    <div class="input-group">
                        <select asp-for="TeacherCourse" class="form-control dselect2 multiselect">
                            @{


                                foreach (var item in tc)
                                {
                                    <option value="@item.Id">@item.Teacher.User.DisplayName</option>
                                }
                            }
                        </select>
                        <div class="input-group-addon">تغییر وضعیت دوره</div>
                        <span asp-validation-for="TeacherCourse" class="text-danger"></span>

                    </div>
                </div>
                <div class="col-md-3">
                    <select asp-for="TeacherCourseIdes" class="form-control dselect2 multiselect" style="width:100%">
                        @{
                            foreach (var item in _listTeacher)
                            {
                                <option value="@item.Id">@item.User.DisplayName</option>
                            }
                        }
                    </select>
                    <span asp-validation-for="TeacherCourseIdes" class="text-danger"></span>

                </div>
            </div>





            <div class="form-group ">
                @Html.LabelFor(model => model.ImageUrl, new { @class = "col-md-3 control-label col-md-push-1" })
                <div class="col-md-6">
                    <img src="@Model.ImageUrl" width="350" height="280" alt="تصویر دوره" />
                    <hr />
                    <div class="input-group">
                        <input type="file" name="ImageUrlFile" value="" />
                        <input asp-for="ImageUrl" class="form-control disabled text-left hidden" value="ImageUrlFile" />
                        <span asp-validation-for="ImageUrl" class="text-danger"></span>

                    </div>
                </div>
            </div>




            <div class="form-group">
                @Html.LabelFor(model => model.CourseStatus, new { @class = "col-md-3 control-label col-md-push-1" })
                <div class="col-md-6">
                    <div class="input-group">
                        <select asp-for="CourseStatus" asp-items="Html.GetEnumSelectList<CourseStatus>()" class="form-control dselect2"></select>
                        <div class="input-group-addon">تغییر وضعیت دوره</div>
                        <span asp-validation-for="CourseStatus" class="text-danger"></span>

                    </div>
                </div>
            </div>




            <div class="form-group ">
                @Html.LabelFor(model => model.StartDate, new { @class = "col-md-3 control-label col-md-push-1" })
                <div class="col-md-6">
                    <div class="input-group">
                        @Html.TextBoxFor(model => model.StartDate, new { @class = "form-control", dir = "ltr" })
                        <div class="input-group-addon">1371/06/03</div>
                        <span asp-validation-for="StartDate" class="text-danger"></span>

                    </div>
                </div>
            </div>


            <div class="form-group">
                @Html.LabelFor(model => model.Price, new { @class = "col-md-3 control-label col-md-push-1" })
                <div class="col-md-6">
                    <div class="input-group">
                        @Html.TextBoxFor(model => model.Price, new { @class = "form-control", dir = "ltr" })
                        <div class="input-group-addon">ریال</div>
                        <span asp-validation-for="Price" class="text-danger"></span>

                    </div>
                </div>
            </div>




            <div class="form-group">
                @Html.LabelFor(model => model.Link, new { @class = "col-md-3 control-label col-md-push-1" })
                <div class="col-md-6">
                    <div class="input-group">
                        @Html.TextBoxFor(model => model.Link, new { @class = "form-control", dir = "ltr" })
                        <div class="input-group-addon">لینک دوره در کلاس مجازی </div>
                        <span asp-validation-for="Link" class="text-danger"></span>

                    </div>
                </div>
            </div>






            <hr />








            <h2>دانشجویان دوره</h2>




        </div>



        <div class="panel-footer">
            <div class="row">
                <div class="col col-md-3 col-xs-6">
                    <button type="submit" class="btn btn-info w100"><i class="fa fa-save"> </i> ذخیره اطلاعات </button>
                </div>
                <div class="col col-md-3 col-xs-6">
                    <a class="btn btn-danger w100" asp-area="@AreaConstants.PanelArea" asp-controller="Home" asp-action="Index"> بازگشت  <i class="fa  fa-angle-double-left"> </i></a>
                </div>
            </div>
        </div>


    </form>
</div>













@section Styles {
    <link href="~/css/fileinput.min.css" rel="stylesheet" asp-append-version="true" />
}

@section Scripts
    {
    <script src="~/js/fileinput.min.js" type="text/javascript" asp-append-version="true"></script>

    <script type="text/javascript">
        function triggerRemoteValidation() {
            $('#@nameof(UserProfileViewModel.UserName)').removeData('previousValue');
            $('form').validate().element('#@nameof(UserProfileViewModel.UserName)');

            $('#@nameof(UserProfileViewModel.Email)').removeData('previousValue');
            $('form').validate().element('#@nameof(UserProfileViewModel.Email)');
        }

    $(document).on('ready', function () {
        $("#userphoto").fileinput({
            rtl: true,
            theme: "fa",
            showUpload: false,
            language:"fa",
            allowedFileExtensions: ["jpg", "png", "gif"]
        });
    });
    </script>


}

src/Microdownload/Areas/Panel/Views/Courses/Index.cshtml
@model IEnumerable<CourseViewModel>

@{
    ViewData["Title"] = "دوره ها";
}
<div class="panel panel-default">
    <div class="panel-heading">
        <div class="row">
            <div class="col-md-6">
                <h3 class="panel-title">@ViewData["Title"]</h3>
            </div>
            <div class="col-md-6">
                <div class="btn-group pull-right">
                    <a class="btn btn-success" href="#" id="btnCreateNew"><i class="fa fa-plus"> </i> افزودن دوره جدید</a>
                </div>
            </div>
        </div>
    </div>



    <div class="panel-body">


        @(Html
                                                              .Grid(Model)
                                                              .Build(columns =>
                                                              {
                                                                  columns.Add(model => model.CourseName).Titled("نام دوره");
                                                                  columns.Add(model => model.CourseStatus).Titled("نوع دوره");
                                                                  columns.Add(model => model.CreatedDate.ToFriendlyPersianDateTextify()).Titled("تاریخ ایجاد");
                                                                  columns.Add(model => model.Price.ToString("N0").ToPersianNumbers()).Titled("قیمت دوره(ریال)");
                                                                  columns.Add(model => model.StartDate.ToFriendlyPersianDateTextify()).Titled("تاریخ شروع دوره");



                                                                  columns.Add(model => $"<a  asp-controller=\"Corses\" asp-action=\"EditCourse\"   href =\"Courses/EditCourse/{model.Id}\" class=\"btn btn-sm btn-info\" style=\"margin-left:10px\">نمایش</a>").Encoded(false);
                                                                  columns.Add(model => $"<a  href=\"#\"  id=\"btnEdit-{model.Id}\" data-edit-id=\"{model.Id}\" class=\"btn btn-sm btn-danger\" style=\"margin-left:10px\">ویرایش</a>").Encoded(false);


                                                              })
                                                                    .Empty("دوره ای یافت نشد")
                                                                    .Filterable()
                                                                    .Sortable()
                                                                    .Pageable(pager =>
                                                                    {
                                                                        pager.ProcessorType = GridProcessorType.Manual;
                                                                        pager.TotalRows = ViewBag.TotalRows;
                                                                        pager.RowsPerPage = 10;
                                                                    })
        )


    </div>



    <div class="panel-footer">
        تعداد کل دوره ها : @Model.Count()
    </div>


</div>



@section Scripts
    {
    <script src="~/server/assets/js/core/MvcGrid.js"></script>
    <script type="text/javascript">
        $(function () {
            $('#btnCreateNew').click(function (e) {
                e.preventDefault();

                $.bootstrapModalAjaxForm({

                    postUrl: '@Url.Action("AddCourse", "Courses")',
                    renderModalPartialViewUrl: '@Url.Action("RenderCourse", "Courses")',
                    renderModalPartialViewData: {},
                    loginUrl: '/Panel/login',
                    beforePostHandler: function () {
                    },
                    completeHandler: function () {
                        location.reload();
                    },
                    errorHandler: function () {
                    }
                });
            });

            $("a[id^='btnEdit']").click(function (e) {
                e.preventDefault();
                var slideId = $(this).data("edit-id");

                $.bootstrapModalAjaxForm({
                    postUrl: '@Url.Action("AddCourse", "Courses")',
                    renderModalPartialViewUrl: '@Url.Action("RenderCourse", "Courses")',
                    renderModalPartialViewData: JSON.stringify({ "id": slideId }),
                    loginUrl: '/Panel/login',
                    beforePostHandler: function () {
                    },
                    completeHandler: function () {
                        location.reload();
                    },
                    errorHandler: function () {
                    }
                });
            });

            $("a[id^='btnDelete']").click(function (e) {
                e.preventDefault();
                var slideId = $(this).data("delete-id");

                $.bootstrapModalAjaxForm({
                    postUrl: '@Url.Action("DeleteInsurance", "Insurance")',
                    renderModalPartialViewUrl: '@Url.Action("RenderDeleteInsurance", "Insurance")',
                    renderModalPartialViewData: JSON.stringify({ "id": slideId }),
                    loginUrl: '/Panel/login',
                    beforePostHandler: function () {
                    },
                    completeHandler: function () {
                        location.reload();
                    },
                    errorHandler: function () {
                    }
                });
            });
        });


    </script>

}

src/Microdownload/Areas/Panel/Views/Courses/_Create.cshtml
@model CourseViewModel
@{List<InstituteViewModel> _listInstitute = (List<InstituteViewModel>)ViewData["ListInstitute"]; }
@{List<TeacherViewModel> _listTeacher = (List<TeacherViewModel>)ViewData["ListTeacher"]; }

<script type="text/javascript">

    $('.dselect2').select2();
    $('#Amount').number(true, 0);

</script>

<partial name="_CustomValidationSummary" />
<form asp-action="AddCourse" method="post" enctype="multipart/form-data" class="form-horizontal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                @if (string.IsNullOrEmpty(Model?.Id.ToString()))
                {
                    <h4 class="modal-title">افزودن دوره جدید</h4>
                }
                else
                {
                    <h4 class="modal-title">ویرایش دوره</h4>
                }
            </div>
            <div class="modal-body">

                <input asp-for="Id" hidden="hidden" />
                <div class="form-group">
                    <label asp-for="CourseName" class="col col-lg-3 control-label"></label>
                    <div class="col col-lg-9 controls">
                        <div class="input-group top15">
                            <input dir="rtl" asp-for="CourseName" class="form-control" />
                            <div class="input-group-addon" dir="ltr">فارسی</div>
                        </div>
                        <span asp-validation-for="CourseName" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group">
                    <label asp-for="TeacherCourseIdes" class="col col-lg-3 control-label"></label>
                    <div class="col col-lg-9 controls">
                        <select asp-for="TeacherCourseIdes" class="form-control dselect2 multiselect" style="width:100%">
                            @{
                                foreach (var item in _listTeacher)
                                {
                                    <option value="@item.Id">@item.User.DisplayName</option>
                                }
                            }
                        </select>
                        <span asp-validation-for="TeacherCourseIdes" class="text-danger"></span>

                    </div>
                </div>

                <div class="form-group">
                    <label asp-for="Link" class="col col-lg-3 control-label"></label>
                    <div class="col col-lg-9 controls">
                        <div class="input-group top15">
                            <input dir="ltr" placeholder="http://" asp-for="Link" class="form-control" />
                            <div class="input-group-addon" dir="ltr">حروف انگلیسی</div>
                        </div>
                        <span asp-validation-for="Link" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group">
                    <label asp-for="Price" class="col col-lg-3 control-label"></label>
                    <div class="col col-lg-9 controls">
                        <div class="input-group top15">
                            <input dir="ltr" asp-for="Price" class="form-control" />
                            <div class="input-group-addon" dir="ltr">عدد انگلیسی | ریال</div>
                        </div>
                        <span asp-validation-for="Price" class="text-danger"></span>
                    </div>
                </div>



            </div>
            <div class="modal-footer">
                <button class="btn btn-primary" type="submit">ثبت</button>
                <button class="btn" data-dismiss="modal" aria-hidden="true">انصراف</button>
            </div>
        </div>
    </div>
</form>

src/Microdownload/Areas/Panel/Views/Courses/_Delete.cshtml
@model CourseViewModel
@{ await Html.RenderPartialAsync("_CustomValidationSummary").ConfigureAwait(false); }
<form asp-action="Delete" method="post" class="form-horizontal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title">حذف دوره @Model.Id</h4>
            </div>
            <div class="modal-body">
                <span class="text-center">
                    آیا می‌خواهید کارمزد 
                    <strong>@Model.CourseName</strong>
                    را حذف کنید؟
                </span>
                <input hidden="hidden" asp-for="Id" />
            </div>
            <div class="modal-footer">
                <button class="btn btn-danger" type="submit">تائید حذف</button>
                <button class="btn" data-dismiss="modal" aria-hidden="true">انصراف</button>
            </div>
        </div>
    </div>
</form>