src/Microdownload/Areas/Panel/Controllers/UserCardController.cs
using System.Threading.Tasks;
using Microdownload.Common.GuardToolkit;
using Microdownload.Common.IdentityToolkit;
using Microdownload.Services.Contracts.Identity;
using Microdownload.Services.Identity;
using Microdownload.ViewModels.Identity;
using DNTBreadCrumb.Core;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microdownload.Areas.Panel;

namespace Microdownload.Areas.Panel.Controllers
{
    [AllowAnonymous]
    [Area(AreaConstants.PanelArea)]
    [BreadCrumb(Title = "برگه‌ی کاربری", UseDefaultRouteUrl = true, Order = 0)]
    public class UserCardController : Controller
    {
        private readonly IApplicationUserManager _userManager;
        private readonly IApplicationRoleManager _roleManager;

        public UserCardController(
            IApplicationUserManager userManager,
            IApplicationRoleManager roleManager)
        {
            _userManager = userManager;
            _userManager.CheckArgumentIsNull(nameof(_userManager));

            _roleManager = roleManager;
            _roleManager.CheckArgumentIsNull(nameof(_roleManager));
        }

        [BreadCrumb(Title = "ایندکس", Order = 1)]
        public async Task<IActionResult> Index(int? id)
        {
            if (!id.HasValue && User.Identity.IsAuthenticated)
            {
                id = User.Identity.GetUserId<int>();
            }

            if (!id.HasValue)
            {
                return View("Error");
            }
            var cuRole = _roleManager.GetRolesForCurrentUser();
            var d = 0;
            foreach (var item in cuRole)
            {
                if (item.Degree > d)
                {
                    d = item.Degree;
                }
            }
            if (User.IsInRole(ConstantRoles.Admin))
            {
                d = 0;
            }
            ViewData["d"] = d;

            var user = await _userManager.FindByIdIncludeUserRolesAsync(id.Value);
            if (user == null)
            {
                return View("NotFound");
            }
            var md = _roleManager.GetRolesForUser(id.Value);
            var model= new UserCardItemViewModel
            {
                User = user,
                ShowAdminParts = User.IsInRole(ConstantRoles.Admin),
                Roles = await _roleManager.GetAllCustomRolesAsync(),
                ActiveTab = UserCardItemActiveTab.UserInfo
            };
            return View(model);
        }

        [ResponseCache(Location = ResponseCacheLocation.None, NoStore = true)]
        public async Task<IActionResult> EmailToImage(int? id)
        {
            if (!id.HasValue)
            {
                return NotFound();
            }

            var fileContents = await _userManager.GetEmailImageAsync(id);
            return new FileContentResult(fileContents, "image/png");
        }

        [BreadCrumb(Title = "لیست نمایندگان آنلاین", Order = 1)]
        public IActionResult OnlineUsers()
        {
            return View();
        }
    }
}

src/Microdownload/Areas/Panel/Views/UserCard/Index.cshtml
@model UserCardItemViewModel

@{
    ViewData["Title"] = $"برگه مشخصات {Model.User.DisplayName}";
}

<partial name="_UserCardItem" model="Model" />

src/Microdownload/Areas/Panel/Views/UserCard/OnlineUsers.cshtml
@{
    ViewData["Title"] = $"نمایندگان آنلاین";
}
<div dir="rtl">
    <cache expires-after="@TimeSpan.FromMinutes(1)">
        <vc:online-users numbers-to-take="100" minutes-to-take="15" show-more-items-link="false"></vc:online-users>
    </cache>
</div>

src/Microdownload/Areas/Panel/Views/UserCard/_UserAdminPart.cshtml
@model UserCardItemViewModel
@{
    var user = Model.User;
}
<div class="top30">
    <div class="col-md-7">
        <table id="all-roles-list" class="table table-striped table-hover table-bordered table-condensed">
            <tr>
                <th class="text-center">ویژگی کاربری</th>
                <th class="text-center">وضعیت</th>
                <th class="text-center">اختیارات</th>
            </tr>
            <tr>
                <td>
                    <span aria-hidden="true" class="fa fa-user"></span>
                    <strong>کد کاربری</strong>
                </td>
                <td class="text-center">@user.UserName</td>
                <td class="text-center">
                    <a asp-controller="UserProfile"
                       asp-action="AdminEdit"
                       asp-route-id="@user.Id"
                       class="btn btn-info btn-xs w100">
                        ویرایش مشخصات
                        <span aria-hidden="true" class="fa fa-edit"></span>
                    </a>
                </td>
            </tr>
            <tr>
                <td>
                    <span aria-hidden="true" class="fa fa-user-circle-o"></span>
                    <strong>وضعیت کاربری</strong>
                </td>
                <td class="text-center">
                    @if (user.IsActive)
                    {
                        <span class="label label-success w100">فعال</span>
                    }
                    else
                    {
                        <span class="label label-warning w100">غیرفعال</span>
                    }
                </td>
                <td class="text-center">
                    <form method="post"
                          asp-controller="UsersManager"
                          asp-action="ChangeUserStat"
                          role="form"
                          data-ajax="true"
                          data-ajax-alert-confirm="وضعیت کاربری @user.DisplayName تغییر کند؟"
                          data-ajax-begin="dataAjaxBegin"
                          data-ajax-success="dataAjaxSuccess"
                          data-ajax-failure="dataAjaxFailure"
                          data-ajax-update="#usercard-@user.Id">
                        <input name="userId" value="@user.Id" type="hidden" />
                        @if (user.IsActive)
                        {
                            <input name="activate" value="false" type="hidden" />
                            <button type="submit" class="btn btn-danger btn-xs w100">
                                غیرفعال شود
                                <span aria-hidden="true" class="fa fa-thumbs-down"></span>
                            </button>
                        }
                        else
                        {
                            <input name="activate" value="true" type="hidden" />
                            <button type="submit" class="btn btn-info btn-xs w100">
                                فعال شود
                                <span aria-hidden="true" class="fa fa-thumbs-up"></span>
                            </button>
                        }
                    </form>
                </td>
            </tr>
            <tr>
                <td>
                    <span aria-hidden="true" class="fa fa-envelope"></span>
                    <strong>
                        وضعیت ایمیل
                    </strong>
                </td>
                <td class="text-center">
                    @if (user.EmailConfirmed)
                    {
                        <span class="label label-success w100">تائید شده</span>
                    }
                    else
                    {
                        <span class="label label-warning w100">تائید نشده</span>
                    }
                </td>
                <td class="text-center">
                    @if (!user.EmailConfirmed)
                    {
                        <form method="post"
                              asp-controller="UsersManager"
                              asp-action="ActivateUserEmailStat"
                              role="form"
                              data-ajax="true"
                              data-ajax-begin="dataAjaxBegin"
                              data-ajax-success="dataAjaxSuccess"
                              data-ajax-failure="dataAjaxFailure"
                              data-ajax-update="#usercard-@user.Id">
                            <input name="userId" value="@user.Id" type="hidden" />
                            <button type="submit" class="btn btn-info btn-xs w100">
                                تائید شود
                                <span aria-hidden="true" class="fa fa-thumbs-up"></span>
                            </button>
                        </form>
                    }
                </td>
            </tr>
            <tr>
                <td>
                    <span aria-hidden="true" class="fa fa-lock"></span>
                    <strong>
                        امکان قفل شدن اکانت
                    </strong>
                </td>
                <td class="text-center">
                    @if (user.LockoutEnabled)
                    {
                        <span class="label label-success w100">فعال</span>
                    }
                    else
                    {
                        <span class="label label-warning w100">غیرفعال</span>
                    }
                </td>
                <td class="text-center">
                    <form method="post"
                          asp-controller="UsersManager"
                          asp-action="ChangeUserLockoutMode"
                          role="form"
                          data-ajax="true"
                          data-ajax-begin="dataAjaxBegin"
                          data-ajax-success="dataAjaxSuccess"
                          data-ajax-failure="dataAjaxFailure"
                          data-ajax-update="#usercard-@user.Id">
                        <input name="userId" value="@user.Id" type="hidden" />
                        @if (user.LockoutEnabled)
                        {
                            <input name="activate" value="false" type="hidden" />
                            <button type="submit" class="btn btn-danger btn-xs w100">
                                غیرفعال شود
                                <span aria-hidden="true" class="fa fa-thumbs-down"></span>
                            </button>
                        }
                        else
                        {
                            <input name="activate" value="true" type="hidden" />
                            <button type="submit" class="btn btn-info btn-xs w100">
                                فعال شود
                                <span aria-hidden="true" class="fa fa-thumbs-up"></span>
                            </button>
                        }
                    </form>
                </td>
            </tr>
            <tr>
                <td>
                    <span aria-hidden="true" class="fa fa-calendar-check-o"></span>
                    <strong>
                        زمان خاتمه قفل شدن اکانت
                    </strong>
                </td>
                <td class="text-center">
                    @if (user.LockoutEnd != null)
                    {
                        @user.LockoutEnd.Value.ToFriendlyPersianDateTextify().ToPersianNumbers()
                    }
                </td>
                <td class="text-center">
                    @if (user.LockoutEnd != null)
                    {
                        <form method="post"
                              asp-controller="UsersManager"
                              asp-action="EndUserLockout"
                              role="form"
                              data-ajax="true"
                              data-ajax-begin="dataAjaxBegin"
                              data-ajax-success="dataAjaxSuccess"
                              data-ajax-failure="dataAjaxFailure"
                              data-ajax-update="#usercard-@user.Id">
                            <input name="userId" value="@user.Id" type="hidden" />
                            <button type="submit" class="btn btn-info btn-xs w100">
                                رفع قفل
                                <span aria-hidden="true" class="fa fa-thumbs-up"></span>
                            </button>
                        </form>
                    }
                </td>
            </tr>
            <tr>
                <td>
                    <span aria-hidden="true" class="fa fa-user-secret"></span>
                    <strong>
                        اعتبارسنجی دو مرحله‌ای
                    </strong>
                </td>
                <td class="text-center">
                    @if (user.TwoFactorEnabled)
                    {
                        <span class="label label-success w100">فعال</span>
                    }
                    else
                    {
                        <span class="label label-warning w100">غیرفعال</span>
                    }
                </td>
                <td class="text-center">
                    <form method="post"
                          asp-controller="UsersManager"
                          asp-action="ChangeUserTwoFactorAuthenticationStat"
                          role="form"
                          data-ajax="true"
                          data-ajax-begin="dataAjaxBegin"
                          data-ajax-success="dataAjaxSuccess"
                          data-ajax-failure="dataAjaxFailure"
                          data-ajax-update="#usercard-@user.Id">
                        <input name="userId" value="@user.Id" type="hidden" />
                        @if (user.TwoFactorEnabled)
                        {
                            <input name="activate" value="false" type="hidden" />
                            <button type="submit" class="btn btn-danger btn-xs w100">
                                غیرفعال شود
                                <span aria-hidden="true" class="fa fa-thumbs-down"></span>
                            </button>
                        }
                        else
                        {
                            <input name="activate" value="true" type="hidden" />
                            <button type="submit" class="btn btn-info btn-xs w100">
                                فعال شود
                                <span aria-hidden="true" class="fa fa-thumbs-up"></span>
                            </button>
                        }
                    </form>
                </td>
            </tr>
        </table>
    </div>
    <div class="col-md-5">

        <form method="post"
              asp-controller="UsersManager"
              asp-action="ChangeUserRoles"
              role="form"
              data-ajax="true"
              data-ajax-begin="dataAjaxBegin"
              data-ajax-success="dataAjaxSuccess"
              data-ajax-failure="dataAjaxFailure"
              data-ajax-update="#usercard-@user.Id">
            <input name="userId" value="@user.Id" type="hidden" />

            <table id="all-roles-list" class="table table-striped table-hover table-bordered table-condensed">
                <tr>
                    <th class="text-center">
                        <span aria-hidden="true" class="fa fa-id-badge"></span>
                        نقش‌های سیستم
                    </th>
                </tr>
                @{
                    if (!User.IsInRole(ConstantRoles.Admin))
                    {
                        int d = int.Parse(ViewData["d"].ToString());

                        foreach (var role in Model.Roles)
                        {


                            var selected = user.Roles.Any(userRole => userRole.RoleId == role.Id) ? "checked" : "";

                            if (role.Degree > d)
                            {
                                <tr>
                                    <td>
                                        <div>
                                            <input type="checkbox" name="roleIds" value="@role.Id" @selected />
                                            @role.Name
                                        </div>
                                    </td>
                                </tr>
                            }
                        }

                    }
                    else
                    {
                        foreach (var role in Model.Roles)
                        {


                            var selected = user.Roles.Any(userRole => userRole.RoleId == role.Id) ? "checked" : "";

                            <tr>
                                <td>
                                    <div>
                                        <input type="checkbox" name="roleIds" value="@role.Id" @selected />
                                        @role.Name
                                    </div>
                                </td>
                            </tr>

                        }
                    }



                }

                <tr>
                    <td>
                        <button type="submit" class="btn btn-info btn-xs top10 w100">
                            اعمال تغییرات نقش‌ها
                            <span aria-hidden="true" class="fa fa-thumbs-up"></span>
                        </button>
                    </td>
                </tr>

            </table>
        </form>

    </div>
</div>

src/Microdownload/Areas/Panel/Views/UserCard/_UserCardItem.cshtml
@model UserCardItemViewModel

@{
    var user = Model.User;
    var adminPartIsActive = Model.ActiveTab == UserCardItemActiveTab.UserAdmin ? "active" : "";
    var userPartIsActive = Model.ActiveTab == UserCardItemActiveTab.UserInfo ? "active" : "";
}

<div class="panel panel-default top30">
    <div class="panel-body">
        <div>
            <div class="row">
                <div class="col-md-12">
                    <h2>
                        <a asp-action="Index" asp-controller="UserCard" asp-route-id="@user.Id">@user.DisplayName</a>
                    </h2>
                </div>
            </div>
            <div>
                <ul class="nav nav-tabs top15" role="tablist">
                    <li role="presentation" class="@userPartIsActive">
                        <a href="#info-@user.Id" aria-controls="info-@user.Id" role="tab" data-toggle="tab">مشخصات</a>
                    </li>
                    @if (Model.ShowAdminParts)
                    {
                        <li role="presentation" class="@adminPartIsActive">
                            <a href="#admin-@user.Id" aria-controls="admin-@user.Id" role="tab" data-toggle="tab">مدیریت کاربر</a>
                        </li>
                    }
                </ul>
                <div class="tab-content">
                    <div role="tabpanel" class="tab-pane @userPartIsActive" id="info-@user.Id">
                        <partial name="~/Areas/Panel/Views/UserCard/_UserInfoPart.cshtml" model="Model" />
                    </div>
                    @if (Model.ShowAdminParts)
                    {
                        <div role="tabpanel" class="tab-pane @adminPartIsActive" id="admin-@user.Id">
                            <partial name="~/Areas/Panel/Views/UserCard/_UserAdminPart.cshtml" model="Model" />
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

src/Microdownload/Areas/Panel/Views/UserCard/_UserInfoPart.cshtml
@model UserCardItemViewModel
@inject IUsersPhotoService PhotoService

@{
    var user = Model.User;
    var photoUrl = PhotoService.GetUserPhotoUrl(user.PhotoFileName);
}

<div class="top30">
    <div class="col-md-4">
        <ul class="media-list">
            <li class="media">
                <img class="img-circle" src="@photoUrl" alt="@user.DisplayName" asp-append-version="true"
                     onerror="this.style.visibility = 'hidden';this.width=0; this.height=0;" />
            </li>
        </ul>
    </div>
    <div class="col-md-4">
        <ul class="media-list">
            <li class="media">
                <span aria-hidden="true" class="fas fa-user"></span>
                <strong>عضو شماره:</strong> @user.Id.ToPersianNumbers()
            </li>
            <li class="media">
                <span aria-hidden="true" class="fas fa-clock"></span>
                <strong>تاریخ عضویت: </strong><span dir="ltr">
                    <abbr title="@user.CreatedDateTime.Value.ToFriendlyPersianDateTextify().ToPersianNumbers()">
                        @user.CreatedDateTime.Value.ToShortPersianDateString(DateTimeOffsetPart.DateTime).ToPersianNumbers()
                    </abbr>
                </span>
            </li>

            @if (user.IsEmailPublic)
            {
                <li class="media">
                    <span aria-hidden="true" class="fas fa-envelope"></span>
                    <img src="@Url.Action(action: "EmailToImage", controller:"UserCard", values: new { id = user.Id })"
                         asp-append-version="true"
                         alt="@user.DisplayName Email" />
                </li>
            }

            @if (!string.IsNullOrWhiteSpace(user.Location))
            {
                <li class="media">
                    <span aria-hidden="true" class="fas fa-home"></span>
                    <strong>محل اقامت:</strong>
                    @user.Location
                </li>
            }

            @if (user.LastVisitDateTime != null)
            {
                <li class="media">
                    <span aria-hidden="true" class="fas fa-calendar-check"></span>
                    <strong>آخرین مراجعه:</strong>
                    @user.LastVisitDateTime.Value.ToFriendlyPersianDateTextify().ToPersianNumbers()
                </li>
            }
        </ul>

    </div>
    <div class="col-md-4">
        <ul class="media-list">
            @if (user.BirthDate.HasValue)
            {
                <li class="media">
                    <span aria-hidden="true" class="fas fa-calendar"></span>
                    <strong>سن:</strong>
                    <abbr title="@user.BirthDate.Value.ToString("yyyy/MM/dd", CultureInfo.InvariantCulture), @user.BirthDate.Value.ToShortPersianDateString(DateTimeOffsetPart.DateTime)">
                        @user.BirthDate.Value.GetAge().ToPersianNumbers()
                    </abbr>
                </li>
            }
        </ul>
    </div>
</div>